# Generated by Django 4.2.1 on 2023-06-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminLogin",
            fields=[
                (
                    "adminid",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=20)),
            ],
        ),
    ]
