# Generated by Django 4.2.1 on 2023-06-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic_app", "0002_alter_adminlogin_adminid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enquery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20)),
                ("phone", models.IntegerField()),
                ("useremail", models.EmailField(max_length=30)),
                ("course", models.CharField(max_length=20)),
                ("message", models.TextField(max_length=100)),
            ],
        ),
    ]
