# Generated by Django 4.2.1 on 2023-06-19 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basic_app", "0004_blog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="blogdate",
        ),
    ]
